-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/Shenzhen/zzff/STVSR/STDAN-main/codes/test_vimeo_ddp.py", line 29, in main_worker
    setup(rank, world_size)
  File "/data/Shenzhen/zzff/STVSR/STDAN-main/codes/test_vimeo_ddp.py", line 17, in setup
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 226, in _env_rendezvous_handler
    master_addr = _get_env_or_raise("MASTER_ADDR")
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 203, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set
